#!/bin/bash

PYGMENTS_STYLE=fruity

echo 'Content-type: text/html'
echo ''

datestr_orig=$(basename "$PATH_TRANSLATED")
datestr_orig=${datestr_orig%%.log}
datestr_new=$(date -d "$datestr_orig" +"%b %d" 2>&1)

case "$QUERY_STRING" in
    *nojoins* | *noparts* | *noquits* )
        sed "/^\[[[:digit:]]\{2\}:[[:digit:]]\{2\}:[[:digit:]]\{2\}\] \*\*\* \(Joins\|Parts\|Quits\): /d" "$PATH_TRANSLATED" 2>&1 | \
        sed "s/\[\([[:digit:]]\{2\}:[[:digit:]]\{2\}:[[:digit:]]\{2\}\)\]/${datestr_new} \1/" | \
        # We need to explicitly set `-o /dev/stdout`, or else pygmentize will cut off most of the output for some reason
        pygmentize -l irc -O full,style=$PYGMENTS_STYLE -f html -o /dev/stdout
        ;;
    * )
        sed "s/\[\([[:digit:]]\{2\}:[[:digit:]]\{2\}:[[:digit:]]\{2\}\)\]/${datestr_new} \1/" "$PATH_TRANSLATED" | \
        # We need to explicitly set `-o /dev/stdout`, or else pygmentize will cut off most of the output for some reason
        pygmentize -l irc -O full,style=$PYGMENTS_STYLE -f html -o /dev/stdout
        ;;
esac
